# -*- coding: utf-8 -*-
"""Копия блокнота "Forecast_coffee_rf.ipynb"

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10QcfXlJongKV7vCa6Vj_pRb7Cd_d4dr7
"""

import pandas as pd
from statsmodels.tsa.arima.model import ARIMA
import warnings
warnings.filterwarnings("ignore")

# ========== 1. ЗАГРУЗКА ДАННЫХ ==========
df = pd.read_csv("coffee_prices_rf.csv",sep=';')  # или .xlsx, если у тебя Excel
print(df.head()) 

# ========== 2. ПОДГОТОВКА ДАННЫХ ДЛЯ МОДЕЛИ ==========
df['date'] = pd.to_datetime(df['date'], format='%d.%m.%Y')
monthly = df.set_index('date')
monthly = monthly.asfreq('MS')

# ========== 3. ОБУЧАЕМ МОДЕЛЬ ARIMA ==========
model = ARIMA(monthly['avg_price'], order=(2, 1, 2))
fitted = model.fit()
print("\n=== ПАРАМЕТРЫ МОДЕЛИ ===")
print(fitted.summary())

# ========== 4. ДЕЛАЕМ ПРОГНОЗ НА 6 МЕСЯЦЕВ ==========
forecast = fitted.get_forecast(steps=6)
pred = forecast.summary_frame(alpha=0.05)
# Создаём таблицу с результатами
result = pred[["mean", "mean_ci_lower", "mean_ci_upper"]].copy()
result.columns = ["yhat", "yhat_lower", "yhat_upper"]
result["is_forecast"] = True
# Добавляем даты для прогноза (следующие 6 месяцев)
last_date = monthly.index[-1]
future_dates = pd.date_range(start=last_date + pd.offsets.MonthBegin(1), periods=6, freq='MS')
result.index = future_dates
result.index.name = 'date'

# ========== 5. СОХРАНЯЕМ ПРОГНОЗ В ФАЙЛ ==========
result.to_csv("forecast_6m.csv",sep=';')
print("\n Прогноз сохранён в файл forecast_6m.csv")
print("\n=== ПРОГНОЗ НА 6 МЕСЯЦЕВ ===")
print(result)